version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - "**/*"
    schedule:
      interval: monthly
    labels:
      - "Status: Review Needed"
      - "Type: Dependencies"
      - "Type: Maintenance"
      - "Type: CI"
      - "Type: Meta"
    open-pull-requests-limit: 20
  - package-ecosystem: npm
    directories:
      - "**/*"
    schedule:
      interval: monthly
    labels:
      - "Status: Review Needed"
      - "Type: Dependencies"
      - "Type: Maintenance"
    open-pull-requests-limit: 20
    groups:
      types:
        patterns:
          - "@types/*"
      eslint:
        patterns:
          - "*eslint*"
