# check on push.
name: check

on: push

jobs:
  editorconfig:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@v2
      - run: editorconfig-checker
  elisp:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@v6.0
        with:
          version: 29.1
      - uses: leotaku/elisp-check@v1.4.1
        with:
          file: typespec-ts-mode.el
