# コミットごとにチェックを行う。
name: check

on: push

jobs:
  editorconfig:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: editorconfig-checker/action-editorconfig-checker@main
      - run: editorconfig-checker
  elisp:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: purcell/setup-emacs@master
        with:
          version: 29.1
      - uses: leotaku/elisp-check@master
        with:
          file: typespec-ts-mode.el
